# Copied from https://github.com/go-swagger/go-swagger

version: "0.0.{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: C:\gopath\src\github.com\wgplaner\wg_planer_server
shallow_clone: true # for startup speed
pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.9.1
  GOCOVMODE: "mode: atomic"
  PATH: C:\gopath\bin;%PATH%

platform:
  - x64

# http://www.appveyor.com/docs/installed-software
install:
  # pre-installed MinGW at C:\MinGW is 32bit only
  # but MSYS2 at C:\msys64 has mingw64
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;%PATH%
  - gcc --version
  - g++ --version

  # upgrade go
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL

  # some helpful output for debugging builds
  - go version
  - go env

  # get the dependencies etc
  - go get -u github.com/stretchr/testify/assert
  - go get -u github.com/davecgh/go-spew/spew
  - go get -u github.com/axw/gocov/gocov
  - go get -u gopkg.in/matm/v1/gocov-html
  - go get -u github.com/cee-dub/go-junit-report
  - go get -u github.com/go-openapi/loads
  - go get -u github.com/go-openapi/runtime
  - go get -u github.com/tylerb/graceful
  - go get -u github.com/jessevdk/go-flags

  # install swagger
  - appveyor DownloadFile https://github.com/go-swagger/go-swagger/releases/download/0.12.0/swagger_windows_amd64.exe -FileName swagger.exe
  - ps: Move-Item .\swagger.exe C:\swagger.exe
  - cd C:\gopath\src\github.com\wgplaner\wg_planer_server
  - ps: New-Item -ItemType "directory" -Name "gen"
  - C:\swagger.exe version
  - C:\swagger.exe generate server -t gen -f .\swagger\swagger.yml --exclude-main -A wgplaner
  - go get -u -f .\gen\...

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %PATH%
  - echo %GOPATH%

test_script:
  - ps: go test -race -v $(go list ./... | sls -n "vendor")

#artifacts:
#  - path: '%GOPATH%\bin\*.exe'
deploy: off
