language: go
go:
  - 1.9.x
  - master
go_import_path: github.com/wgplaner/wg_planer_server/

addons:
  artifacts: true

env:
  - WGPLANER_ROOT=$HOME/gopath/src/github.com/wgplaner/wg_planer_server/

install:
  - cp -v config/config.example.toml config/config.toml
  - cp -v config/serviceAccountKey.example.json config/serviceAccountKey.json
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger
  - go install github.com/go-swagger/go-swagger/cmd/swagger
  - sed -i 's/- https/- http/g' ./swagger.yml
  - swagger version
  - swagger generate server -t . -f swagger.yml --exclude-main --skip-models -P models.User -A wgplaner
  - go get -v ./cmd/wgplaner-api

script:
  - go tool vet .
  - go build -o "build/wg_planer_server" cmd/wgplaner-api/wgplaner-api.go
  - ls -la
  - go test -race -v ./...
  - ./scripts/coverage.sh

before_deploy:
  - mkdir -p build/config && cp config/* build/config
  - wget -O swagger-codegen-cli.jar https://oss.sonatype.org/content/repositories/releases/io/swagger/swagger-codegen-cli/2.2.3/swagger-codegen-cli-2.2.3.jar
  - java -jar swagger-codegen-cli.jar generate -i swagger.yml -l html2 -o build/api_doc_html
  - java -jar swagger-codegen-cli.jar generate -i swagger.yml -l java --library=okhttp-gson -o build/android_client
  - cd build/android_client && ./gradlew jar
  - cd ${TRAVIS_BUILD_DIR}
  - tar -zcvf wg_planer_server.tar.gz build
  - ./scripts/bintray_deploy.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f integration.coverage.out -F integration
  - bash <(curl -s https://codecov.io/bash) -f unit.coverage.out -F unittests

notifications:
  email:
    on_success: change
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: HZjzgdGqZwL3GZOAdsyKacdn96HnCJ8CnmB4x+AHmnSQwz2iWUQU0/kK/JDz7cdIEFdWSQzd0ugaJv8LpNoRdo/4LgWF0eKQw32IFqVzE37Ie+zyTdM7XaRGm9bkZRwo3rsoFNydrKV3Wkufb27oZCUEgddp+cCCfZtkbt3LfDiZHHjHR9GFFveIFPQGps/Y/wEwExgZeEd/mlItKUIJvdNe8rlNPjeAG+CzbZzHrDknktouvfPjDHD+G2ItaBsaV5YCenSBQrWKyxkHQQjb/M/xtfxeS+4/BLZ7mBDkkufo1kPJMa394hueBPhnA0rwtrTVZZy8/1T70wbZQ/INgmeHF5Vi89rpugzn0OOh3Zw2ZoKg8IfxzHapUw8D5qz9x3zVoVXCCfF5ST3aY9N+zCxBgjuG6gE7uao/fHfEV0TFCKpWXu81f5Kbcny5qT1qwE5Bs2BGILMPrvfqTQ35yn3FkoHoFuxz0CjTj8jewWSEWWPKB2dSPevxSqgNBuiW/qrqHzO+JVHej9YJlk6X4HaSlzSR6CgfcoHwSJDEEhJxwy9dfFVeHEMgY/kBTQJQTRye3CYeFV2aUP4j2sHrVzMpHoQqhuUG90gT58enXlmPwuRc+i6CURkxDYyLIvF3v661xajeyExOVLhwnZ7L9k65pH01Pd7v/EwjMpfQyvY=
  file: wg_planer_server.tar.gz
  skip_cleanup: true
  on:
    tags: true

deploy:
  provider: bintray
  skip_cleanup: true
  on:
    branch: master
    condition: -f ./scripts/bintray.json
  user: bugwelle
  key:
    secure: r+LUmf0cgZsXBlYnlCmQZslST1G9gsVcPh82ZyOaMwSwJ+jmreBzAlrJSNqphlhbtWgp09ur9tNy7aJ6J/3jzS5IJw4XegnYEzkPxefL9ABgKrsaFZReTXCFgatctQVnuV2wX8l8Ng1UpcEXJu93CVx5va0KjYWAeQ++xdsFdF2yubxlHHso/ml8mpNZddxYBz/kRLhfCeZICcptp++YyEVU1/LwOoNFQ+fRrU11HuCRBos/CARRb/cA5rdxoSHAlEsBGPsJmMRplLQZdIrRMiy4eTzkx15tM6zEW0aFnm3fwNiA09Qsqxaho9kv8eh/ecwObfXyRG+MRZ5dKG6MCgFZ2EGyOx3g4cJdqhwT/09b3eVfMNZmBuN2ymGpOtyjYLDsly001IWS5OdYZz8TwJGQgj8qA8mIQgzG1mKDqVxFK+LoAyzCJr4QRfJAjRSKGFAg8waY6BFjE66qhRl+xbKrRKhWJ3putyZg5sMhQ+hVe4IEsyk8nNcB4UxgYbIi6ilclC6+a20eCnLKo0KfTtHV8YqoE0H/t/tRLcSnsR8teY1CHKqZQwnEsZ0dC/nkXCiv3+yJc4cNxvw40TpbPXMlCE3T6eaBP9vFnn0zeGC5yqMtYDPwd7ISNDHPLM3jVW3Ju/41V6h4gNhFZiU+ovk6nu4emvolEPTcM1p1QV0=
  file: ./scripts/bintray.json
