language: go

go:
  - 1.9.x
  - master

before_install:
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger
  - go install github.com/go-swagger/go-swagger/cmd/swagger
  - swagger version
  - swagger generate server -t gen -f swagger.yml --exclude-main -A wgplaner
  - go get -v

script:
  - go build -o "wg_planer_server" main.go
  - go test -race -v ./...

notifications:
  email:
    on_success: change
    on_failure: always
