language: go
go:
  - 1.9.x
  - 1.10.x
  - master
go_import_path: github.com/wgplaner/wg_planer_server/

addons:
  artifacts: true

env:
  - WGPLANER_ROOT=$HOME/gopath/src/github.com/wgplaner/wg_planer_server/

install:
  - cp -v config/config.example.toml config/config.toml
  - cp -v config/serviceAccountKey.example.json config/serviceAccountKey.json
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger
  - go install github.com/go-swagger/go-swagger/cmd/swagger
  - sed -i 's/- https/- http/g' ./swagger.yml
  - swagger version
  - swagger generate server -t . -f swagger.yml --exclude-main --skip-models -P models.User -A wgplaner
  - go get -v ./cmd/wgplaner-api

script:
  - go tool vet .
  - go build -o "build/wg_planer_server" cmd/wgplaner-api/wgplaner-api.go
  - ls -la
  - go test -race -v ./...
  - ./scripts/coverage.sh
  - mkdir -p build/config && cp config/* build/config
  - wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar -O swagger-codegen-cli.jar
  - java -jar swagger-codegen-cli.jar generate -i swagger.yml -l html2 -o build/api_doc_html
  - java -jar swagger-codegen-cli.jar generate -i swagger.yml -l java --library=okhttp-gson -o build/android_client
  - cd build/android_client && chmod +x gradlew
  - ./gradlew jar

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - bash <(curl -s https://codecov.io/bash) -f integration.coverage.out -F integration
  - bash <(curl -s https://codecov.io/bash) -f unit.coverage.out -F unittests
  - ./scripts/bintray_deploy.sh

notifications:
  email:
    on_success: change
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: HZjzgdGqZwL3GZOAdsyKacdn96HnCJ8CnmB4x+AHmnSQwz2iWUQU0/kK/JDz7cdIEFdWSQzd0ugaJv8LpNoRdo/4LgWF0eKQw32IFqVzE37Ie+zyTdM7XaRGm9bkZRwo3rsoFNydrKV3Wkufb27oZCUEgddp+cCCfZtkbt3LfDiZHHjHR9GFFveIFPQGps/Y/wEwExgZeEd/mlItKUIJvdNe8rlNPjeAG+CzbZzHrDknktouvfPjDHD+G2ItaBsaV5YCenSBQrWKyxkHQQjb/M/xtfxeS+4/BLZ7mBDkkufo1kPJMa394hueBPhnA0rwtrTVZZy8/1T70wbZQ/INgmeHF5Vi89rpugzn0OOh3Zw2ZoKg8IfxzHapUw8D5qz9x3zVoVXCCfF5ST3aY9N+zCxBgjuG6gE7uao/fHfEV0TFCKpWXu81f5Kbcny5qT1qwE5Bs2BGILMPrvfqTQ35yn3FkoHoFuxz0CjTj8jewWSEWWPKB2dSPevxSqgNBuiW/qrqHzO+JVHej9YJlk6X4HaSlzSR6CgfcoHwSJDEEhJxwy9dfFVeHEMgY/kBTQJQTRye3CYeFV2aUP4j2sHrVzMpHoQqhuUG90gT58enXlmPwuRc+i6CURkxDYyLIvF3v661xajeyExOVLhwnZ7L9k65pH01Pd7v/EwjMpfQyvY=
  file: wg_planer_server.tar.gz
  skip_cleanup: true
  on:
    tags: true

deploy:
  provider: bintray
  skip_cleanup: true
  on:
    branch: master
    condition: "-f ./scripts/bintray.json"
  user: bugwelle
  key:
    secure: belROymz+H+U/vsuFelRnIyvh2Nt2nGB3KpdU3GCuTFcYHXN2DQ9gMSKeIp9l79k+e1pqrKAC9QSDpfjtOpBpafFai/jaioK3ZrdE7p33PiF/WWrV1IxK6x4Sx5THATQCCa9rjnOCPramaWqAXVasAUL2Z5qs6KkYOO0iqPPI8rCzlapVCUFZh5Dzsjy+lriyhZTMwS6ab0L1YSJSq3IC+TlYrNENXXXOA5r+cJMks2Hsq1QWGi3QzDq/KoTGc7Kwr9JCDY2Bcrf2YW5aCULGsG3vicGb8yqNZrmqetWculq1bpqSh8RED/qUKg94AzYqymGWBXOhIj3va/RprFhFt3ygLt01WWT/lo54IdEQV9dkXknqtKZli7N4IVpfSQaDpkS0hZc95WGdmyNcsPMPTG2z2pl8jADVOiz5mx3x1aAfejtnlwq4YYdIeIfrwZ5gQJAoH64t4Os4lYUSW/byfJ4NdSPJr5DGTsGSx3WLMnus03Il7O6fUBZLnjTz8YdMOvMHMYKt1sTwzAJl/z1pz5hzWNVVVDCkfIO3b38nS1PT33ciDGxeBljuC6h/NbGQwKm1v0/hDW9MNx0rMC/1SHxTYEn/l0y00joavkCY59kViRc2+dgRHbH5e+yuzENR/75KNu3wsSb0u78CYJkxDPbybJYSwuYH1w4pyYG2Fc=
  file: "${TRAVIS_BUILD_DIR}/scripts/bintray.json"
