# WGPlaner Configuration File

[server]
port = 3000

[auth]
ignore_firebase = false # Whether not to use firebase
firebase_project_id = "<Your Project Name>"
firebase_server_key = "<Your Key Here>"

[data]
user_image_dir     = "data/users"               # Directory has to exist!
user_image_default = "data/default_profile.jpg" # File has to exist!

[database]
driver  = "sqlite"
log_sql = true

# Set if driver == "sqlite"
sqlite_file = "database.sqlite"

# Set if driver == "mysql"
mysql_server   = "localhost"
mysql_port     = 3306
mysql_user     = "WGPlaner"
mysql_password = "my_secret"
mysql_db_name  = "wgplaner_db"

[mail]
send_testmail = false
smtp_port     = 25
smtp_host     = "mail.example.com"
smtp_user     = "info@example.com"
smtp_identity = "info@example.com"
smtp_password = "my_secret"
